name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm install    
      - name: Generate build
        run: npm run build
      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v1
        with:
          name: react-github-actions-build
          path: build
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v1
        with:
          name: react-github-actions-build
      - name: Zip build
        uses: thedoctor0/zip-release@master
        with:
          filename: bonjack-tools-website-release.zip
          path: react-github-actions-build
      # Upload as an artifact of the current workflow
      - name: Upload build zip artifact
        uses: actions/upload-artifact@v1
        with:
          name: bonjack-tools-website-release.zip
          path: bonjack-tools-website-release.zip
